/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSupervisorIndexRouteImport } from './routes/_app/supervisor/index'
import { Route as AppStudentIndexRouteImport } from './routes/_app/student/index'
import { Route as AppSupervisorProjectsRouteImport } from './routes/_app/supervisor/projects'
import { Route as AppStudentSubmitRouteImport } from './routes/_app/student/submit'
import { Route as AppStudentResultsRouteImport } from './routes/_app/student/results'
import { Route as AppSupervisorGradeProjectIdRouteImport } from './routes/_app/supervisor/grade.$projectId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupervisorIndexRoute = AppSupervisorIndexRouteImport.update({
  id: '/supervisor/',
  path: '/supervisor/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentIndexRoute = AppStudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorProjectsRoute = AppSupervisorProjectsRouteImport.update({
  id: '/supervisor/projects',
  path: '/supervisor/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentSubmitRoute = AppStudentSubmitRouteImport.update({
  id: '/student/submit',
  path: '/student/submit',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentResultsRoute = AppStudentResultsRouteImport.update({
  id: '/student/results',
  path: '/student/results',
  getParentRoute: () => AppRoute,
} as any)
const AppSupervisorGradeProjectIdRoute =
  AppSupervisorGradeProjectIdRouteImport.update({
    id: '/supervisor/grade/$projectId',
    path: '/supervisor/grade/$projectId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student/results': typeof AppStudentResultsRoute
  '/student/submit': typeof AppStudentSubmitRoute
  '/supervisor/projects': typeof AppSupervisorProjectsRoute
  '/student/': typeof AppStudentIndexRoute
  '/supervisor/': typeof AppSupervisorIndexRoute
  '/supervisor/grade/$projectId': typeof AppSupervisorGradeProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student/results': typeof AppStudentResultsRoute
  '/student/submit': typeof AppStudentSubmitRoute
  '/supervisor/projects': typeof AppSupervisorProjectsRoute
  '/student': typeof AppStudentIndexRoute
  '/supervisor': typeof AppSupervisorIndexRoute
  '/supervisor/grade/$projectId': typeof AppSupervisorGradeProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/student/results': typeof AppStudentResultsRoute
  '/_app/student/submit': typeof AppStudentSubmitRoute
  '/_app/supervisor/projects': typeof AppSupervisorProjectsRoute
  '/_app/student/': typeof AppStudentIndexRoute
  '/_app/supervisor/': typeof AppSupervisorIndexRoute
  '/_app/supervisor/grade/$projectId': typeof AppSupervisorGradeProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/student/results'
    | '/student/submit'
    | '/supervisor/projects'
    | '/student/'
    | '/supervisor/'
    | '/supervisor/grade/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/student/results'
    | '/student/submit'
    | '/supervisor/projects'
    | '/student'
    | '/supervisor'
    | '/supervisor/grade/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/reset-password'
    | '/_app/student/results'
    | '/_app/student/submit'
    | '/_app/supervisor/projects'
    | '/_app/student/'
    | '/_app/supervisor/'
    | '/_app/supervisor/grade/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/supervisor/': {
      id: '/_app/supervisor/'
      path: '/supervisor'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof AppSupervisorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/': {
      id: '/_app/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AppStudentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor/projects': {
      id: '/_app/supervisor/projects'
      path: '/supervisor/projects'
      fullPath: '/supervisor/projects'
      preLoaderRoute: typeof AppSupervisorProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/submit': {
      id: '/_app/student/submit'
      path: '/student/submit'
      fullPath: '/student/submit'
      preLoaderRoute: typeof AppStudentSubmitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/results': {
      id: '/_app/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof AppStudentResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/supervisor/grade/$projectId': {
      id: '/_app/supervisor/grade/$projectId'
      path: '/supervisor/grade/$projectId'
      fullPath: '/supervisor/grade/$projectId'
      preLoaderRoute: typeof AppSupervisorGradeProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppStudentResultsRoute: typeof AppStudentResultsRoute
  AppStudentSubmitRoute: typeof AppStudentSubmitRoute
  AppSupervisorProjectsRoute: typeof AppSupervisorProjectsRoute
  AppStudentIndexRoute: typeof AppStudentIndexRoute
  AppSupervisorIndexRoute: typeof AppSupervisorIndexRoute
  AppSupervisorGradeProjectIdRoute: typeof AppSupervisorGradeProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppStudentResultsRoute: AppStudentResultsRoute,
  AppStudentSubmitRoute: AppStudentSubmitRoute,
  AppSupervisorProjectsRoute: AppSupervisorProjectsRoute,
  AppStudentIndexRoute: AppStudentIndexRoute,
  AppSupervisorIndexRoute: AppSupervisorIndexRoute,
  AppSupervisorGradeProjectIdRoute: AppSupervisorGradeProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
